title: Proyecto Introduccion 
description: Todo lo aprendido en el  parcial 
author: Samuel Valencia 
correo electrónico : samuelvalencia780@gmail.com
avatar :/ Imagen 2020-08-17 a 18.18.02.jpeg

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
  card: summary
logo: Imagen 2020-08-17 a 18.18.02.jpeg
social:
  name: Samuel Valencia Mosquera 
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
