title: Proyecto Introduccion 
description: Todo lo aprendido en el  parcial 
author: Samuel Valencia 
avatar: /logo.png
email: samuelvalencia780@gmail.com
---
Mi nombre es Dennys Samuel Valencia Mosquera, tengo 19 años me gusta el deporte aunque actualmente no lo práctico, me gustan hacer deportes extremos cuando viajo o descubrir cosas nuevas, estudio Ingeniería en Software  y la finalidad de esta página web es poder enseñar lo aprendido en este parcial en la Universidad Estatal de Guayaquil.
---
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: SamuelValencia
  card: summary
logo: logo.png
social:
  name: Samuel Valencia Mosquera 
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
